### ISSUE TITLE
[smove] script execution (transaction support)

### ISSUE THREAD

**Issue by asmie** [eigerco/smove#1]
Support for generating transactions by either calling `execute_script` extrinsic or saving serialized arguments to the file.

**Comment by Rqnsom** [comment]
https://github.com/eigerco/smove/pull/23
https://github.com/eigerco/smove/pull/21
https://github.com/eigerco/smove/pull/20
https://github.com/eigerco/smove/pull/18
https://github.com/eigerco/smove/pull/17
https://github.com/eigerco/smove/pull/16
